version: '3.8'

services:
  app:
    image: 'ammezie/laravel-coolify:latest'
    volumes:
      - '.:/var/www/html'
      - './conf/nginx/:/etc/nginx/conf.d/'
      - './conf/nginx/:/etc/supervisor/conf.d/'
  worker:
    image: 'ammezie/laravel-coolify:latest'
    command: ["php", "/var/www/html/artisan", "queue:work", "--tries=3"]
    volumes:
      - '.:/var/www/html'
      - './conf/nginx/:/etc/nginx/conf.d/'
      - './conf/nginx/:/etc/supervisor/conf.d/'

